services:
  # FRONTEND ESTÁTICO (PHP + Apache) – súper rápido y barato
  - type: web
    name: infieles-frontend
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /status.php

  # BACKEND API (Node.js)
  - type: web
    name: infieles-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      DATABASE_URL: 
        fromDatabase:
          name: DBS_INF
          property: connectionString
      NODE_ENV: production
