services:
  - type: web
    name: infieles-frontend
    env: docker
    plan: free
    healthCheckPath: /

  - type: web
    name: infieles-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: DBS_INF
          property: connectionString
      - key: NODE_ENV
        value: production
